### ISSUE TITLE
can't run your example code

### ISSUE THREAD

**Issue by sprabowo** [surmon-china/naivebayes#1]
i've tried to run your example code
```
// 导入
const NaiveBayes = require('naivebayes')

// 实例化（创建分类器）
const classifier = new NaiveBayes()

// 学习文本和分类，teach it positive phrases
classifier.learn('amazing, awesome movie!! Yeah!! Oh boy.', 'positive')
classifier.learn('Sweet, this is incredibly, amazing, perfect, great!!', 'positive')

// 学习不同文本和分类，teach it a negative phrase
classifier.learn('terrible, shitty thing. Damn. Sucks!!', 'negative')

// 判断文本归属，now ask it to categorize a document it has never seen before
classifier.categorize('awesome, cool, amazing!! Yay.')
```

```
/var/www/html/dum/lowrsy-smart/node_modules/naivebayes/dist/naive-bayes.js:87
      if (!this.categories.includes(categoryName)) {
                           ^

TypeError: this.categories.includes is not a function
    at NaiveBayes.initializeCategory (/var/www/html/dum/lowrsy-smart/node_modules/naivebayes/dist/naive-bayes.js:87:28)
    at NaiveBayes.learn (/var/www/html/dum/lowrsy-smart/node_modules/naivebayes/dist/naive-bayes.js:111:12)
    at Object.<anonymous> (/var/www/html/dum/lowrsy-smart/1.js:8:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by surmon-china** [comment]
Update your browser please or require the pollfill.
